@startuml
'https://plantuml.com/class-diagram
class Computer {
    - HDD: String
    - RAM: String
    - isGraphicsCardEnabled: boolean
    - isBluetoothEnabled: boolean

    - Computer(builder: ComputerBuilder)
}


class ComputerBuilder {
    - HDD: String
    - RAM: String
    - isGraphicsCardEnabled: boolean
    - isBluetoothEnabled: boolean

    + ComputerBuilder(hdd: String, ram String)
    + setGraphicsCardEnabled(boolean): ComputerBuilder
    + setBluetoothEnabled(boolean): ComputerBuilder
    + build(): Computer
}

Computer +-- ComputerBuilder

@enduml