@startuml
'https://plantuml.com/class-diagram
hide empty members


interface SomeService {
    process(): void
}

class SomeServiceImpl implements SomeService {
    process(): void
}

class SomeServiceProxy implements SomeService {
    - {static} object: SomeService
    + process(): void
    - getObject(): SomeService
}
SomeServiceProxy o-> SomeServiceImpl

@enduml